@echo off
echo Starting Boardy Frontend...
cd frontend
echo Installing dependencies if needed...
if not exist node_modules (
    echo Installing npm dependencies...
    npm install
)
echo Starting development server...
npm run dev
pause