import type { ThemeConfig } from 'antd';

export const boardyTheme: ThemeConfig = {
  token: {
    colorPrimary: '#7C6DD8',
    colorSuccess: '#A8E6CF',
    colorWarning: '#FFD3B6',
    colorError: '#FF6B6B',
    colorInfo: '#7C6DD8',

    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FFFFFF',
    colorBgSpotlight: '#FAFAFA',

    colorText: '#2D3436',
    colorTextSecondary: '#636E72',
    colorTextTertiary: '#B2BEC3',
    colorTextQuaternary: '#DFE6E9',

    colorBorder: '#E0E0E0',
    colorBorderSecondary: '#F0F0F0',

    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    borderRadiusXS: 6,

    boxShadow: '0 2px 8px rgba(124, 109, 216, 0.08)',
    boxShadowTertiary: '0 4px 16px rgba(124, 109, 216, 0.10)',
    boxShadowSecondary: '0 8px 24px rgba(124, 109, 216, 0.14)',

    fontFamily: "'Nunito', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,
    fontSizeXL: 20,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,

    margin: 16,
    marginLG: 24,
    marginMD: 20,
    marginSM: 12,
    marginXS: 8,
    marginXXS: 4,

    padding: 16,
    paddingLG: 24,
    paddingMD: 20,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,

    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,

    colorLink: '#7C6DD8',
    colorLinkHover: '#6A5BCA',
    colorLinkActive: '#5949BB',
  },
  components: {
    Button: {
      colorPrimary: '#7C6DD8',
      colorPrimaryHover: '#6A5BCA',
      colorPrimaryActive: '#5949BB',
      colorPrimaryBorder: '#7C6DD8',
      borderRadius: 12,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontWeight: 600,
      defaultBg: '#FFFFFF',
      defaultColor: '#2D3436',
      defaultBorderColor: '#E0E0E0',
      defaultHoverBg: '#F8F5FF',
      defaultHoverColor: '#7C6DD8',
      defaultHoverBorderColor: '#7C6DD8',
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E0E0E0',
      colorPrimaryBorderHover: '#7C6DD8',
      colorPrimaryBorder: '#7C6DD8',
      colorText: '#2D3436',
      colorTextPlaceholder: '#B2BEC3',
      borderRadius: 12,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingInline: 16,
    },
    Card: {
      colorBgContainer: '#FFFFFF',
      colorBorderSecondary: '#F0F0F0',
      borderRadiusLG: 16,
      boxShadowTertiary: '0 4px 12px rgba(124, 109, 216, 0.06)',
      headerBg: 'transparent',
      actionsBg: 'transparent',
      actionsLiMargin: '12px 0',
    },
    Modal: {
      colorBgElevated: '#FFFFFF',
      borderRadiusLG: 20,
      paddingContentHorizontal: 24,
      paddingContentVertical: 16,
    },
    Tabs: {
      colorBgContainer: 'transparent',
      cardBg: '#F8F5FF',
      itemColor: '#636E72',
      itemSelectedColor: '#7C6DD8',
      itemHoverColor: '#2D3436',
      titleFontSize: 14,
      cardHeight: 40,
      horizontalMargin: '0',
      cardPadding: '8px 16px',
    },
    Menu: {
      colorBgContainer: '#FFFFFF',
      colorItemBg: 'transparent',
      colorItemBgHover: '#F8F5FF',
      colorItemBgSelected: '#F8F5FF',
      colorItemText: '#2D3436',
      colorItemTextHover: '#2D3436',
      colorItemTextSelected: '#7C6DD8',
      borderRadius: 8,
      itemHeight: 40,
      itemPaddingInline: 16,
    },
    Dropdown: {
      colorBgElevated: '#FFFFFF',
      borderRadiusLG: 12,
      controlHeight: 40,
      fontSize: 14,
    },
    Avatar: {
      colorBgContainer: '#F8F5FF',
      colorText: '#2D3436',
      borderRadius: 20,
    },
    Tag: {
      borderRadius: 8,
      fontSize: 12,
    },
    Message: {
      colorBgElevated: '#FFFFFF',
      borderRadiusLG: 12,
    },
    Spin: {
      colorPrimary: '#7C6DD8',
    },
    DatePicker: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E0E0E0',
      borderRadius: 12,
      controlHeight: 40,
    },
    Tooltip: {
      colorBgElevated: '#FFFFFF',
      colorText: '#7C6DD8',
      borderRadius: 8,
      fontSize: 12,
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    Popover: {
      colorBgElevated: '#FFFFFF',
      borderRadiusLG: 12,
      fontSize: 14,
    },
    Alert: {
      borderRadius: 12,
      fontSize: 14,
    },
  },
};